POST http://localhost:5000/api/v1/products HTTP/1.1
content-type: application/json

{
    "name": "producto 1",
    "price": 650,
    "stock": 5,
    "dateUpdated": "2022-07-06T00:33:22.226Z",
    "dateCreated": "2022-07-01T00:33:22.226Z"
}